# Generated by Django 2.2.2 on 2019-06-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default='00:00', verbose_name='Время начала')),
                ('end_time', models.DateTimeField(default='00:01', verbose_name='Время окончания')),
            ],
            options={
                'verbose_name': 'бронь',
                'verbose_name_plural': 'брони',
                'db_table': 'Booking',
            },
        ),
    ]
