# Generated by Django 2.2.2 on 2019-06-22 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(default=datetime.datetime(2019, 6, 22, 20, 46, 18, 368093), verbose_name='Время окончания')),
            ],
            options={
                'verbose_name': 'бронь',
                'verbose_name_plural': 'брони',
                'db_table': 'Booking',
            },
        ),
    ]
