# Generated by Django 2.2.2 on 2019-06-23 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190622_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 23, 11, 8, 49, 761948), verbose_name='Время окончания'),
        ),
    ]
