# Generated by Django 2.2.2 on 2019-06-23 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190623_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 23, 12, 22, 53, 311406), verbose_name='Время окончания'),
        ),
    ]
