# Generated by Django 2.2.2 on 2019-06-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default=' ', max_length=120, verbose_name='заголовок')),
                ('description', models.TextField(max_length=2000, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'ресурс',
                'verbose_name_plural': 'ресурсы',
                'db_table': 'Resourses',
            },
        ),
    ]
